/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module IWfs;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import wfs_types;

interface IWfs {
  WfsAck wfsPost(ref const(WfsFile) wf);
  WfsFile wfsRead(string name);
  WfsAck wfsDel(string name);

  enum methodMeta = [
    TMethodMeta(`wfsPost`, 
      [TParamMeta(`wf`, 1)]
    ),
    TMethodMeta(`wfsRead`, 
      [TParamMeta(`name`, 1)]
    ),
    TMethodMeta(`wfsDel`, 
      [TParamMeta(`name`, 1)]
    )
  ];
}
