/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module wfs_constants;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import wfs_types;

immutable(int) wfsprotocolversion;
immutable(string) wfsprotocolversionName;

static this() {
  wfsprotocolversion = 1;

  wfsprotocolversionName = "0.0.1";
}
