/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module wfs_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

struct WfsAck {
  int status;
  
  mixin TStructHelpers!([
    TFieldMeta(`status`, 1, TReq.OPTIONAL)
  ]);
}

struct Wfs {
  int status;
  
  mixin TStructHelpers!([
    TFieldMeta(`status`, 1, TReq.OPTIONAL)
  ]);
}

struct WfsFile {
  string name;
  string fileBody;
  string fileType;
  
  mixin TStructHelpers!([
    TFieldMeta(`name`, 1, TReq.OPTIONAL),
    TFieldMeta(`fileBody`, 2, TReq.OPTIONAL),
    TFieldMeta(`fileType`, 3, TReq.OPTIONAL)
  ]);
}

