<?php
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class WfsFile
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'data',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'name',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'compress',
            'isRequired' => false,
            'type' => TType::BYTE,
        ),
    );

    /**
     * @var string
     */
    public $data = null;
    /**
     * @var string
     */
    public $name = null;
    /**
     * @var int
     */
    public $compress = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['data'])) {
                $this->data = $vals['data'];
            }
            if (isset($vals['name'])) {
                $this->name = $vals['name'];
            }
            if (isset($vals['compress'])) {
                $this->compress = $vals['compress'];
            }
        }
    }

    public function getName()
    {
        return 'WfsFile';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->data);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BYTE) {
                        $xfer += $input->readByte($this->compress);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('WfsFile');
        if ($this->data !== null) {
            $xfer += $output->writeFieldBegin('data', TType::STRING, 1);
            $xfer += $output->writeString($this->data);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->name !== null) {
            $xfer += $output->writeFieldBegin('name', TType::STRING, 2);
            $xfer += $output->writeString($this->name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->compress !== null) {
            $xfer += $output->writeFieldBegin('compress', TType::BYTE, 3);
            $xfer += $output->writeByte($this->compress);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
