<?php
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface WfsIfaceIf
{
    /**
     * @param \WfsFile $file
     * @return \WfsAck
     */
    public function Append(\WfsFile $file);
    /**
     * @param string $path
     * @return \WfsAck
     */
    public function Delete($path);
    /**
     * @param string $path
     * @param string $newpath
     * @return \WfsAck
     */
    public function Rename($path, $newpath);
    /**
     * @param \WfsAuth $wa
     * @return \WfsAck
     */
    public function Auth(\WfsAuth $wa);
    /**
     * @param string $path
     * @return \WfsData
     */
    public function Get($path);
    /**
     * @return int
     */
    public function Ping();
}
