--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'wfs_constants'

WfsAck = __TObject:new{
  status
}

function WfsAck:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I32 then
        self.status = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function WfsAck:write(oprot)
  oprot:writeStructBegin('WfsAck')
  if self.status then
    oprot:writeFieldBegin('status', TType.I32, 1)
    oprot:writeI32(self.status)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

Wfs = __TObject:new{
  status
}

function Wfs:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I32 then
        self.status = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function Wfs:write(oprot)
  oprot:writeStructBegin('Wfs')
  if self.status then
    oprot:writeFieldBegin('status', TType.I32, 1)
    oprot:writeI32(self.status)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

WfsFile = __TObject:new{
  name,
  fileBody,
  fileType
}

function WfsFile:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.STRING then
        self.name = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.fileBody = iprot:readString()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.STRING then
        self.fileType = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function WfsFile:write(oprot)
  oprot:writeStructBegin('WfsFile')
  if self.name then
    oprot:writeFieldBegin('name', TType.STRING, 1)
    oprot:writeString(self.name)
    oprot:writeFieldEnd()
  end
  if self.fileBody then
    oprot:writeFieldBegin('fileBody', TType.STRING, 2)
    oprot:writeString(self.fileBody)
    oprot:writeFieldEnd()
  end
  if self.fileType then
    oprot:writeFieldBegin('fileType', TType.STRING, 3)
    oprot:writeString(self.fileType)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end