#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant wfsprotocolversion => 1;

use constant wfsprotocolversionName => "0.0.1";

1;
