/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wfs_CONSTANTS_H
#define wfs_CONSTANTS_H

#include "wfs_types.h"



class wfsConstants {
 public:
  wfsConstants();

  int32_t wfsprotocolversion;
  std::string wfsprotocolversionName;
};

extern const wfsConstants g_wfs_constants;



#endif
