/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "wfs_constants.h"



const wfsConstants g_wfs_constants;

wfsConstants::wfsConstants() {
  wfsprotocolversion = 1;

  wfsprotocolversionName = "0.0.1";

}



