/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

public static class wfsConstants
{
  /// <summary>
  /// 内部版本号
  /// </summary>
  public const int wfsprotocolversion = 1;
  /// <summary>
  /// 外部版本号
  /// </summary>
  public const string wfsprotocolversionName = "0.0.1";
}
