#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

# 返回对象
class WfsAck
  include ::Thrift::Struct, ::Thrift::Struct_Union
  STATUS = 1

  FIELDS = {
    # 状态
    STATUS => {:type => ::Thrift::Types::I32, :name => 'status', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

# 返回对象
class Wfs
  include ::Thrift::Struct, ::Thrift::Struct_Union
  STATUS = 1

  FIELDS = {
    # 状态
    STATUS => {:type => ::Thrift::Types::I32, :name => 'status', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

# 文件对象
class WfsFile
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NAME = 1
  FILEBODY = 2
  FILETYPE = 3

  FIELDS = {
    # 名称
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name', :optional => true},
    # 对象
    FILEBODY => {:type => ::Thrift::Types::STRING, :name => 'fileBody', :binary => true, :optional => true},
    # 类型
    FILETYPE => {:type => ::Thrift::Types::STRING, :name => 'fileType', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

