#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'wfs_types'

Wfsprotocolversion = 1

WfsprotocolversionName = %q"0.0.1"

